import { useState } from "react";
import { Link } from "@tanstack/react-router";
import {
  Sparkles,
  Network,
  Cpu,
  Database,
  Zap,
  Snowflake,
  Activity,
  ArrowDown,
  ArrowUp,
  ChevronRight,
  ExternalLink,
} from "../icons";
import { trackEvent } from "../../lib/analytics";

interface LayerData {
  id: string;
  number: string;
  name: string;
  category: string;
  icon: typeof Sparkles;
  description: string;
  inputs: string;
  outputs: string;
  link: string;
}

const LAYERS: LayerData[] = [
  {
    id: "layer-1",
    number: "01",
    name: "Users / AI Applications",
    category: "Demand Origin",
    icon: Sparkles,
    description:
      "AI workloads, inference serving, and end-user tasks initiating demand requirements down the physical stack.",
    inputs: "Application requests, user traffic, batch training datasets",
    outputs: "Compute demand signals, throughput targets, latency SLA bounds",
    link: "/infrastructure/ai-ready",
  },
  {
    id: "layer-2",
    number: "02",
    name: "Network & Connectivity",
    category: "Regional Fabric",
    icon: Network,
    description:
      "Regional low-latency interconnects, edge routing, and diversified transit paths linking infrastructure sites.",
    inputs: "External traffic, inter-node synchronization batches",
    outputs: "Low-latency packet delivery, path failover signals",
    link: "/infrastructure/network",
  },
  {
    id: "layer-3",
    number: "03",
    name: "Compute Layer",
    category: "AI-Ready Systems",
    icon: Cpu,
    description:
      "High-density server hardware and accelerator clusters engineered for sustained high utilisation.",
    inputs: "Workload instruction streams, network data batches",
    outputs: "Processed output, electrical power draw, concentrated heat dissipation",
    link: "/infrastructure/compute",
  },
  {
    id: "layer-4",
    number: "04",
    name: "Storage & Data Layer",
    category: "Resilient Data Services",
    icon: Database,
    description:
      "High-throughput NVMe tiers and persistent object storage maintaining training pipelines without I/O stalls.",
    inputs: "Training datasets, checkpoint read/write calls",
    outputs: "High-speed streaming data batches, durable snapshot retention",
    link: "/infrastructure/storage",
  },
  {
    id: "layer-5",
    number: "05",
    name: "Energy Management",
    category: "Power Visibility",
    icon: Zap,
    description:
      "Utility feeds, UPS systems, and per-rack power monitoring instrumentation providing complete power visibility.",
    inputs: "Substation grid feeds, compute power draw demands",
    outputs: "Conditioned voltage, granular per-rack kilowatt telemetry",
    link: "/energy/monitoring",
  },
  {
    id: "layer-6",
    number: "06",
    name: "Cooling Infrastructure",
    category: "Thermal Control",
    icon: Snowflake,
    description:
      "Precision airflow and thermal loops calibrated dynamically to remove heat generated by compute density.",
    inputs: "Compute thermal dissipation, ambient temperature",
    outputs: "Extracted thermal load, temperature gradient telemetry",
    link: "/energy/cooling",
  },
  {
    id: "layer-7",
    number: "07",
    name: "Monitoring & Automation",
    category: "Operational Intelligence",
    icon: Activity,
    description:
      "Cross-stack observability and event-driven automation correlating operational signals across all layers.",
    inputs: "Power, thermal, network, and compute operational signals",
    outputs: "Anomaly alerts, cooling loop adjustments, workload pacing commands",
    link: "/automation/monitoring",
  },
];

export function SevenLayerStack() {
  const [selectedLayer, setSelectedLayer] = useState<string>("layer-3");
  const active = LAYERS.find((l) => l.id === selectedLayer) || LAYERS[2];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      {/* Left: The 7-Layer Vertical Stack (7 Cols) */}
      <div className="lg:col-span-7 flex flex-col gap-2 relative">
        {/* Signal Direction Labels */}
        <div className="flex items-center justify-between text-[11px] font-mono text-[#64748B] px-3 pb-1">
          <div className="flex items-center gap-1.5 text-[#06B6D4]">
            <ArrowDown size={13} />
            <span>Demand Flow (Downward)</span>
          </div>
          <div className="flex items-center gap-1.5 text-[#10B981]">
            <ArrowUp size={13} />
            <span>Operational Signals (Upward)</span>
          </div>
        </div>

        {LAYERS.map((layer) => {
          const Icon = layer.icon;
          const isSelected = selectedLayer === layer.id;

          return (
            <button
              key={layer.id}
              onClick={() => {
                setSelectedLayer(layer.id);
                trackEvent({
                  tab: "Infrastructure",
                  event: "infra_stack_layer_select",
                  value: `Layer ${layer.number}: ${layer.name}`,
                });
              }}
              className={`w-full p-3.5 sm:p-4 rounded-xl border text-left transition-all flex items-center justify-between group ${
                isSelected
                  ? "bg-[#1A2234] border-[#10B981] shadow-lg shadow-[#10B981]/10 translate-x-1"
                  : "bg-[#121824] border-[#1E293B] hover:border-[#334155] hover:bg-[#161E2E]"
              }`}
            >
              <div className="flex items-center gap-3.5">
                <span className="font-mono text-xs text-[#94A3B8] font-semibold w-6">
                  {layer.number}
                </span>

                <div
                  className={`w-8 h-8 rounded-lg flex items-center justify-center transition-colors ${
                    isSelected
                      ? "bg-[#10B981] text-[#070A0E]"
                      : "bg-[#0B0F17] text-[#10B981] border border-[#1E293B]"
                  }`}
                >
                  <Icon size={16} />
                </div>

                <div>
                  <h4 className="text-sm font-semibold text-white group-hover:text-[#10B981] transition-colors">
                    {layer.name}
                  </h4>
                  <span className="text-[11px] font-mono text-[#64748B]">{layer.category}</span>
                </div>
              </div>

              <ChevronRight
                size={16}
                className={`transition-transform ${
                  isSelected ? "text-[#10B981] translate-x-0.5" : "text-[#475569]"
                }`}
              />
            </button>
          );
        })}
      </div>

      {/* Right: Layer Inspector Card (5 Cols) */}
      <div className="lg:col-span-5 sticky top-28">
        <div className="rounded-2xl border border-[#334155] bg-[#121824] p-6 shadow-2xl">
          <div className="flex items-center justify-between pb-4 mb-4 border-b border-[#1E293B]">
            <span className="text-xs font-mono text-[#10B981] uppercase tracking-wider">
              Layer {active.number} Telemetry Inspector
            </span>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#1E293B] text-[#94A3B8]">
              {active.category}
            </span>
          </div>

          <h3 className="text-xl font-bold text-white mb-2">{active.name}</h3>

          <p className="text-xs text-[#94A3B8] leading-relaxed mb-6">{active.description}</p>

          <div className="space-y-4 mb-6">
            <div className="p-3 rounded-lg border border-[#1E293B] bg-[#0B0F17]">
              <span className="text-[10px] font-mono text-[#06B6D4] uppercase tracking-wider block mb-1">
                Inputs Received
              </span>
              <p className="text-xs text-[#CBD5E1]">{active.inputs}</p>
            </div>

            <div className="p-3 rounded-lg border border-[#1E293B] bg-[#0B0F17]">
              <span className="text-[10px] font-mono text-[#10B981] uppercase tracking-wider block mb-1">
                Outputs Delivered
              </span>
              <p className="text-xs text-[#CBD5E1]">{active.outputs}</p>
            </div>
          </div>

          <Link
            to={active.link}
            className="w-full py-2.5 px-4 rounded-lg bg-[#1E293B] hover:bg-[#10B981] hover:text-[#070A0E] text-white text-xs font-semibold transition-all flex items-center justify-center gap-2 group"
          >
            <span>Explore Dedicated Submenu</span>
            <ExternalLink size={13} className="transition-transform group-hover:translate-x-0.5" />
          </Link>
        </div>
      </div>
    </div>
  );
}
