/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutSlugRouteImport } from './routes/about/$slug'
import { Route as AutomationIndexRouteImport } from './routes/automation/index'
import { Route as AutomationSlugRouteImport } from './routes/automation/$slug'
import { Route as EnergyIndexRouteImport } from './routes/energy/index'
import { Route as EnergySlugRouteImport } from './routes/energy/$slug'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure/index'
import { Route as InfrastructureSlugRouteImport } from './routes/infrastructure/$slug'
import { Route as RegionsIndexRouteImport } from './routes/regions/index'
import { Route as RegionsSlugRouteImport } from './routes/regions/$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as SustainabilityIndexRouteImport } from './routes/sustainability/index'
import { Route as SustainabilitySlugRouteImport } from './routes/sustainability/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSlugRoute = AboutSlugRouteImport.update({
  id: '/about/$slug',
  path: '/about/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationSlugRoute = AutomationSlugRouteImport.update({
  id: '/automation/$slug',
  path: '/automation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyIndexRoute = EnergyIndexRouteImport.update({
  id: '/energy/',
  path: '/energy/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergySlugRoute = EnergySlugRouteImport.update({
  id: '/energy/$slug',
  path: '/energy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureSlugRoute = InfrastructureSlugRouteImport.update({
  id: '/infrastructure/$slug',
  path: '/infrastructure/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsIndexRoute = RegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsSlugRoute = RegionsSlugRouteImport.update({
  id: '/regions/$slug',
  path: '/regions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityIndexRoute = SustainabilityIndexRouteImport.update({
  id: '/sustainability/',
  path: '/sustainability/',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilitySlugRoute = SustainabilitySlugRouteImport.update({
  id: '/sustainability/$slug',
  path: '/sustainability/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/about/$slug': typeof AboutSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/energy/$slug': typeof EnergySlugRoute
  '/infrastructure/$slug': typeof InfrastructureSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sustainability/$slug': typeof SustainabilitySlugRoute
  '/about/': typeof AboutIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/energy/': typeof EnergyIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/sustainability/': typeof SustainabilityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/about/$slug': typeof AboutSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/energy/$slug': typeof EnergySlugRoute
  '/infrastructure/$slug': typeof InfrastructureSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sustainability/$slug': typeof SustainabilitySlugRoute
  '/about': typeof AboutIndexRoute
  '/automation': typeof AutomationIndexRoute
  '/energy': typeof EnergyIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/regions': typeof RegionsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/sustainability': typeof SustainabilityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/about/$slug': typeof AboutSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/energy/$slug': typeof EnergySlugRoute
  '/infrastructure/$slug': typeof InfrastructureSlugRoute
  '/regions/$slug': typeof RegionsSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/sustainability/$slug': typeof SustainabilitySlugRoute
  '/about/': typeof AboutIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/energy/': typeof EnergyIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/regions/': typeof RegionsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/sustainability/': typeof SustainabilityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/about/$slug'
    | '/automation/$slug'
    | '/energy/$slug'
    | '/infrastructure/$slug'
    | '/regions/$slug'
    | '/solutions/$slug'
    | '/sustainability/$slug'
    | '/about/'
    | '/automation/'
    | '/energy/'
    | '/infrastructure/'
    | '/regions/'
    | '/solutions/'
    | '/sustainability/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/about/$slug'
    | '/automation/$slug'
    | '/energy/$slug'
    | '/infrastructure/$slug'
    | '/regions/$slug'
    | '/solutions/$slug'
    | '/sustainability/$slug'
    | '/about'
    | '/automation'
    | '/energy'
    | '/infrastructure'
    | '/regions'
    | '/solutions'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/about/$slug'
    | '/automation/$slug'
    | '/energy/$slug'
    | '/infrastructure/$slug'
    | '/regions/$slug'
    | '/solutions/$slug'
    | '/sustainability/$slug'
    | '/about/'
    | '/automation/'
    | '/energy/'
    | '/infrastructure/'
    | '/regions/'
    | '/solutions/'
    | '/sustainability/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  AboutSlugRoute: typeof AboutSlugRoute
  AutomationSlugRoute: typeof AutomationSlugRoute
  EnergySlugRoute: typeof EnergySlugRoute
  InfrastructureSlugRoute: typeof InfrastructureSlugRoute
  RegionsSlugRoute: typeof RegionsSlugRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SustainabilitySlugRoute: typeof SustainabilitySlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
  EnergyIndexRoute: typeof EnergyIndexRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
  RegionsIndexRoute: typeof RegionsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  SustainabilityIndexRoute: typeof SustainabilityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$slug': {
      id: '/about/$slug'
      path: '/about/$slug'
      fullPath: '/about/$slug'
      preLoaderRoute: typeof AboutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$slug': {
      id: '/automation/$slug'
      path: '/automation/$slug'
      fullPath: '/automation/$slug'
      preLoaderRoute: typeof AutomationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/': {
      id: '/energy/'
      path: '/energy'
      fullPath: '/energy/'
      preLoaderRoute: typeof EnergyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy/$slug': {
      id: '/energy/$slug'
      path: '/energy/$slug'
      fullPath: '/energy/$slug'
      preLoaderRoute: typeof EnergySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/$slug': {
      id: '/infrastructure/$slug'
      path: '/infrastructure/$slug'
      fullPath: '/infrastructure/$slug'
      preLoaderRoute: typeof InfrastructureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/': {
      id: '/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof RegionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions/$slug': {
      id: '/regions/$slug'
      path: '/regions/$slug'
      fullPath: '/regions/$slug'
      preLoaderRoute: typeof RegionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability/': {
      id: '/sustainability/'
      path: '/sustainability'
      fullPath: '/sustainability/'
      preLoaderRoute: typeof SustainabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability/$slug': {
      id: '/sustainability/$slug'
      path: '/sustainability/$slug'
      fullPath: '/sustainability/$slug'
      preLoaderRoute: typeof SustainabilitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  AboutSlugRoute: AboutSlugRoute,
  AutomationSlugRoute: AutomationSlugRoute,
  EnergySlugRoute: EnergySlugRoute,
  InfrastructureSlugRoute: InfrastructureSlugRoute,
  RegionsSlugRoute: RegionsSlugRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SustainabilitySlugRoute: SustainabilitySlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  AutomationIndexRoute: AutomationIndexRoute,
  EnergyIndexRoute: EnergyIndexRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  SustainabilityIndexRoute: SustainabilityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
